version: '2'

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
        - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./data/registry_data:/var/lib/registry

  jenkins:
    image: shimmi/jenkins
    env_file: .env
    group_add:
      - docker
    volumes:
      - ./data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sentry: &sentry
    image: soloidx/sentry
    env_file: .env
    links:
      - redis:redis
      - postgres:postgres
      - smtp:smtp

  sentry-web:
    <<: *sentry
    command: sentry run web
    ports:
      - 9000:9000
    depends_on:
      - sentry-worker
      - sentry-cron

  sentry-worker:
    <<: *sentry
    command: sentry run worker

  sentry-cron:
    <<: *sentry
    command: sentry run cron

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  smtp:
    image: tianon/exim4
